In [521]:
import gym
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [522]:
class QLearning():
    """
    Implements Q Learning Algorithm for openai-gym's FrozenLake8x8 Environment
    
    SFFF       (S: starting point, safe)
    FHFH       (F: frozen surface, safe)
    FFFH       (H: hole, fall to your doom)
    HFFG       (G: goal, where the frisbee is located)
    
    Agent starts at S and most traverse this icy field until they land on tile G!
    If they land on H or if they take 200 steps, the agent loses
    """
    
    
    def __init__(self, learning_rate, exploitation_rate, discount_rate):
        """
        Initializes hyper parameters
        
        @param learning_rate: INTEGER between 0 and 1 representing the size of a learning step
        @param exploitation_rate: INTEGER between 0 and 1 representing what fraction
            of the time do we choose to pick our current most optimal action rather than
            choose a random action. 
        @param discount_rate: INTEGER between 0 and 1 indicating our lookout discount rate
        """
        self.alpha = learning_rate
        self.epsilon = exploitation_rate
        self.beta = discount_rate
        self.env = gym.make('FrozenLake8x8-v0')
        
        # 2-D Matrix where rows are states and columns represent actions
        self.qtable = np.zeros((self.env.observation_space.n, self.env.action_space.n))
        self.actions = range(self.env.action_space.n)

        
    def policy(self, state, exploration=True):
        """
        Maps states to actions
        
        @param state: INTEGER representing agent's current state
        @return: INTEGER representing chosen action given some state
        """
        if exploration and np.random.uniform() > self.epsilon:
            return np.random.choice(self.actions)
        
        # Tie breaker for maximum reward
        max_value = max(self.qtable[state])
        max_indices = [i for i, val in enumerate(self.qtable[state]) if val == max_value]
        return np.random.choice(max_indices)
    
    
    def updateQtable(self, state, action, reward, next_state):
        """
        Updates a qtable element. Follows the formula:
        Q(s, a) = Q(s, a) + alpha * [Reward(s, a) + beta * max(Q'(s', for all a')) - Q(s, a)]
        """
        self.qtable[state][action] += self.alpha * \
            (reward + self.beta * max(self.qtable[next_state]) - self.qtable[state][action])
        
        
    def train(self, epochs):
        """
        Train RL Agent
        
        @params epochs: INTEGER representing number of training iterations
        """
        i = 1
        for epoch in range(epochs):
            if epoch/epochs > i/5:
                print("\nFinished {0}/5 epochs".format(i))
                i += 1
            self.sample(update_qtable=True)
        print("\nFinished {0}/5 epochs".format(i))
    
    
    @staticmethod
    def reward_modifier(reward, done):
        """
        Modifies reward to some extent. For example, uses inputs of
        reward and done param to determine whether the agent moved, whether they
        died, and whether they won and adjusts the reward accordingly. Without
        this function, reward will be 1 on win and 0 otherwise. We want to penalize
        excess moves, dying, and give a big reward towards winning.
        
        @param reward: INTEGER representing reward from some state, action
        @param done: BOOLEAN representing whether episode has ended
        @returns: INTEGER representing modified reward
        """
        if reward == 0 and done:
            # Died or time ran out
            reward = -200
            
        elif reward == 1:
            # Got to goal
            reward = 500
            
        else:
            # Moved
            reward = -1
            
        return reward
    
    
    def sample(self, update_qtable=False):
        """
        Undergoes one episode
        
        @param update_qtable: BOOLEAN indicating whether this episode
        will update the qtable
        """
        next_state = self.env.reset()
        
        done = False
        if not update_qtable:
            self.env.render()
            
        while not done:
            state = next_state
            action = self.policy(state, update_qtable)
            
            next_state, reward, done, info = self.env.step(action)
            
            if not update_qtable:
                self.env.render()
            else:
                reward = self.reward_modifier(reward, done)
                self.updateQtable(state, action, reward, next_state)
        

In [523]:
agent = QLearning(.05, .99, 1)

In [524]:
agent.train(5000)
print(agent.qtable)


Finished 1/5 epochs

Finished 2/5 epochs

Finished 3/5 epochs

Finished 4/5 epochs

Finished 5/5 epochs
[[ 2.41203056e+02  2.33582524e+02  2.67598916e+02  2.53908320e+02]
 [ 2.02066775e+02  2.17717493e+02  2.09514394e+02  2.70779621e+02]
 [ 1.74624119e+02  2.07057284e+02  2.76919413e+02  2.02088059e+02]
 [ 1.86075549e+02  1.94148915e+02  2.81769690e+02  2.03597809e+02]
 [ 1.99918568e+02  2.08090627e+02  2.85942959e+02  2.18178856e+02]
 [ 2.17011738e+02  1.81001460e+02  2.90879294e+02  1.94796496e+02]
 [ 2.19341421e+02  2.04796949e+02  2.95924350e+02  2.05874740e+02]
 [ 2.29131202e+02  1.48389651e+02  3.04825963e+02  2.13804926e+02]
 [ 2.07052771e+02  1.77610565e+02  1.58820031e+02  2.67778499e+02]
 [ 1.21067558e+02  1.21712179e+02  1.32759554e+02  2.70744477e+02]
 [ 1.04641409e+02  1.72716051e+02  1.22776327e+02  2.75147225e+02]
 [ 9.30533793e+01  7.26870411e+01  5.90447746e+01  2.78733300e+02]
 [ 1.89598945e+02  2.14682869e+02  1.88687820e+02  2.83538953e+02]
 [ 1.24026426e+02  1.682

In [525]:
agent.sample()


SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFF