In [5]:
import gym
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
class QLearning():
    """
    Implements Q Learning Algorithm for openai-gym's FrozenLake8x8 Environment
    
    SFFF       (S: starting point, safe)
    FHFH       (F: frozen surface, safe)
    FFFH       (H: hole, fall to your doom)
    HFFG       (G: goal, where the frisbee is located)
    
    Agent starts at S and most traverse this icy field until they land on tile G!
    If they land on H or if they take 200 steps, the agent loses
    """
    
    
    def __init__(self, learning_rate, exploitation_rate, discount_rate):
        """
        Initializes hyper parameters
        
        @param learning_rate: INTEGER between 0 and 1 representing the size of a learning step
        @param exploitation_rate: INTEGER between 0 and 1 representing what fraction
            of the time do we choose to pick our current most optimal action rather than
            choose a random action. 
        @param discount_rate: INTEGER between 0 and 1 indicating our lookout discount rate
        """
        self.alpha = learning_rate
        self.epsilon = exploitation_rate
        self.beta = discount_rate
        self.env = gym.make('FrozenLake8x8-v0')
        
        # 2-D Matrix where rows are states and columns represent actions
        self.qtable = np.zeros((self.env.observation_space.n, self.env.action_space.n))
        self.actions = range(self.env.action_space.n)

        
    def policy(self, state, exploration=True):
        """
        Maps states to actions
        
        @param state: INTEGER representing agent's current state
        @return: INTEGER representing chosen action given some state
        """
        if exploration and np.random.uniform() > self.epsilon:
            return np.random.choice(self.actions)
        
        # Tie breaker for maximum reward
        max_value = max(self.qtable[state])
        max_indices = [i for i, val in enumerate(self.qtable[state]) if val == max_value]
        return np.random.choice(max_indices)
    
    
    def updateQtable(self, state, action, reward, next_state):
        """
        Updates a qtable element. Follows the formula:
        Q(s, a) = Q(s, a) + alpha * [Reward(s, a) + beta * max(Q'(s', for all a')) - Q(s, a)]
        """
        self.qtable[state][action] += self.alpha * \
            (reward + self.beta * max(self.qtable[next_state]) - self.qtable[state][action])
        
        
    def train(self, epochs):
        """
        Train RL Agent
        
        @params epochs: INTEGER representing number of training iterations
        """
        i = 1
        for epoch in range(epochs):
            if epoch/epochs > i/5:
                print("\nFinished {0}/5 epochs".format(i))
                i += 1
            self.sample(update_qtable=True)
        print("\nFinished {0}/5 epochs".format(i))
    
    
    @staticmethod
    def reward_modifier(reward, done):
        """
        Modifies reward to some extent. For example, uses inputs of
        reward and done param to determine whether the agent moved, whether they
        died, and whether they won and adjusts the reward accordingly. Without
        this function, reward will be 1 on win and 0 otherwise. We want to penalize
        excess moves, dying, and give a big reward towards winning.
        
        @param reward: INTEGER representing reward from some state, action
        @param done: BOOLEAN representing whether episode has ended
        @returns: INTEGER representing modified reward
        """
        if reward == 0 and done:
            # Died or time ran out
            reward = -200
            
        elif reward == 1:
            # Got to goal
            reward = 500
            
        else:
            # Moved
            reward = -1
            
        return reward
    
    
    def sample(self, update_qtable=False):
        """
        Undergoes one episode
        
        @param update_qtable: BOOLEAN indicating whether this episode
        will update the qtable
        """
        next_state = self.env.reset()
        
        done = False
        if not update_qtable:
            self.env.render()
            
        while not done:
            state = next_state
            action = self.policy(state, update_qtable)
            
            next_state, reward, done, info = self.env.step(action)
            
            if not update_qtable:
                self.env.render()
            else:
                reward = self.reward_modifier(reward, done)
                self.updateQtable(state, action, reward, next_state)

In [7]:
agent = QLearning(.05, .99, 1)

In [8]:
agent.train(5000)
print(agent.qtable)


Finished 1/5 epochs

Finished 2/5 epochs

Finished 3/5 epochs

Finished 4/5 epochs

Finished 5/5 epochs
[[ 165.56493891  270.46357675  141.357841    134.50158567]
 [ 197.29919416  193.90262073  279.39292389  186.40419883]
 [ 223.27655807  254.23330442  291.742825    265.06759041]
 [ 173.24547283  225.99257314  186.2329271   301.61006214]
 [ 123.69069975  139.67395268  320.48603683  167.02303332]
 [ 108.17127776  103.51751179  339.47033799  132.60299993]
 [ 288.82479382  291.89159171  350.60487677  309.19061094]
 [ 350.88149322  275.92521596  255.48625558  303.321905  ]
 [ 132.86287232  175.88222814  264.12943755  166.5820788 ]
 [ 173.59990536  200.08129712  209.6394663   274.55479793]
 [ 161.57092162  164.76630659  190.78645361  283.30204936]
 [ -15.94948814   55.58445234   51.1129392   289.86781333]
 [ 104.23535376  288.26872345  131.88638485  111.49579545]
 [ 107.86099136  160.11778017  337.71405516  112.03170717]
 [ 292.92972072  289.18594185  355.49344882  248.88717329]
 [ 289.113

In [9]:
agent.sample()


SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Down)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Down)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Down)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
